<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>

	  <IsPackable>true</IsPackable>
	  <PackageId>Exceler</PackageId>
	  <Version>1.0.0-beta.1</Version>
	  <Authors>Amir Mahdiyar</Authors>
	  <Description>A high-performance, memory-efficient, and pipeline-based Excel reader/writer for .NET applications.</Description>
	  <PackageTags>excel;epplus;export;import;performance;chunking</PackageTags>
	  <RepositoryUrl>https://github.com/YourUsername/Exceler</RepositoryUrl>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>

	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.2" />
  </ItemGroup>

</Project>
