using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Exceler.Abstractions;
using Exceler.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TestExcelerWebApi.Dtos;
using TestExcelerWebApi.Inputs;

namespace TestExcelerWebApi.Controllers
{
    /// <summary>
    /// Showcase controller demonstrating full Round-Trip Excel processing:
    /// Any Excel generated by an Export endpoint can be fed directly into a corresponding Import endpoint!
    /// 
    /// Matched Pairs:
    /// 1. GET export-inputs   / export-template -> POST import (or import-chunks)
    /// 2. GET export-excel    / export-stream   -> POST import-excel
    /// 3. GET export-records                    -> POST import-records
    /// 4. POST echo-roundtrip                   -> Upload input Excel, returns styled processed Excel
    /// </summary>
    [ApiController]
    [Route("api/financial-orders")]
    public class FinancialOrdersController : ControllerBase
    {
        private readonly IExcelReader _excelReader;
        private readonly IExcelWriter _excelWriter;

        public FinancialOrdersController(IExcelReader excelReader, IExcelWriter excelWriter)
        {
            _excelReader = excelReader;
            _excelWriter = excelWriter;
        }

        #region 1. Raw Input Endpoints (Matching POST import & import-chunks)

        /// <summary>
        /// [PAIR 1 - EXPORT] Exports sample raw input rows (19 columns).
        /// Feed this output directly to POST /api/financial-orders/import or /import-chunks!
        /// </summary>
        [HttpGet("export-inputs")]
        public async Task<IActionResult> ExportInputsSampleAsync()
        {
            var sampleInputs = GenerateSampleInputs(10);
            var memoryStream = new MemoryStream();

            await _excelWriter.WriteAsync(sampleInputs, memoryStream, "Orders Input");
            memoryStream.Position = 0;

            return File(
                memoryStream,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Financial_Orders_Inputs_Sample.xlsx"
            );
        }

        /// <summary>
        /// [PAIR 1 - EXPORT TEMPLATE] Downloads a blank/single-row template for raw input.
        /// Feed this output directly to POST /api/financial-orders/import!
        /// </summary>
        [HttpGet("export-template")]
        public async Task<IActionResult> ExportTemplateAsync()
        {
            var templateRows = GenerateSampleInputs(1);
            var memoryStream = new MemoryStream();

            await _excelWriter.WriteAsync(templateRows, memoryStream, "Orders Input");
            memoryStream.Position = 0;

            return File(
                memoryStream,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Financial_Order_Import_Template.xlsx"
            );
        }

        /// <summary>
        /// [PAIR 1 - IMPORT] Reads raw input Excel (from export-inputs or export-template).
        /// Performs Async Validation (IAsyncExcelValidator) and Financial Calculations (IAsyncExcelProcessor).
        /// </summary>
        [HttpPost("import")]
        public IActionResult ImportFinancialOrders(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return BadRequest(new { Error = "No file uploaded or file is empty." });

            if (!file.FileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
                return BadRequest(new { Error = "Only .xlsx Excel files are supported." });

            using var stream = file.OpenReadStream();

            // Pipeline: Read FinancialOrderInput -> Validate (Async) -> Process (Async) -> FinancialOrderDto
            var results = _excelReader.Read<FinancialOrderInput, FinancialOrderDto>(stream).ToList();

            var validOrders = results.Where(r => r.IsValid).Select(r => r.Data).ToList();
            var invalidOrders = results.Where(r => !r.IsValid).Select(r => new
            {
                RowNumber = r.RowIndex,
                Errors = r.Errors
            }).ToList();

            return Ok(new
            {
                Message = "Input Excel read, validated, and processed successfully.",
                TotalRowsRead = results.Count,
                ValidCount = validOrders.Count,
                InvalidCount = invalidOrders.Count,
                ValidOrders = validOrders,
                ValidationFailures = invalidOrders
            });
        }

        /// <summary>
        /// [PAIR 1 - CHUNKED IMPORT] Reads large raw input Excel in chunks.
        /// Feed the file from export-inputs here for memory-efficient batch processing.
        /// </summary>
        [HttpPost("import-chunks")]
        public async Task<IActionResult> ImportFinancialOrdersChunksAsync(
            IFormFile file,
            [FromQuery] int chunkSize = 5,
            CancellationToken cancellationToken = default)
        {
            if (file == null || file.Length == 0)
                return BadRequest(new { Error = "No file uploaded or file is empty." });

            if (chunkSize <= 0) chunkSize = 5;

            using var stream = file.OpenReadStream();

            int chunkIndex = 0;
            int totalProcessed = 0;
            int totalValid = 0;
            int totalInvalid = 0;
            var chunkSummaries = new List<object>();

            await foreach (var chunk in _excelReader.ReadInChunksAsync<FinancialOrderInput, FinancialOrderDto>(
                stream,
                chunkSize,
                sheetName: null,
                cancellationToken: cancellationToken))
            {
                chunkIndex++;
                totalProcessed += chunk.Count;

                var validCount = chunk.Count(x => x.IsValid);
                var invalidCount = chunk.Count(x => !x.IsValid);

                totalValid += validCount;
                totalInvalid += invalidCount;

                chunkSummaries.Add(new
                {
                    ChunkNumber = chunkIndex,
                    ChunkSize = chunk.Count,
                    ValidCount = validCount,
                    InvalidCount = invalidCount,
                    ErrorsInChunk = chunk.Where(x => !x.IsValid).Select(x => new { x.RowIndex, x.Errors }).ToList()
                });
            }

            return Ok(new
            {
                Message = "Chunked import processing completed successfully.",
                TotalChunks = chunkIndex,
                TotalRecordsProcessed = totalProcessed,
                TotalValid = totalValid,
                TotalInvalid = totalInvalid,
                ChunkDetails = chunkSummaries
            });
        }

        #endregion

        #region 2. Full Styled Report Endpoints (Matching POST import-excel)

        /// <summary>
        /// [PAIR 2 - EXPORT] Exports full 27-column styled financial report (FinancialOrderDto).
        /// Includes palette colors, explicit widths, and currency/percent formats.
        /// Feed this output directly to POST /api/financial-orders/import-excel!
        /// </summary>
        [HttpGet("export-excel")]
        public async Task<IActionResult> ExportFinancialOrdersAsync()
        {
            var sampleOrders = GenerateSampleDtos(15);
            var memoryStream = new MemoryStream();

            await _excelWriter.WriteAsync(sampleOrders, memoryStream, "Financial Orders");
            memoryStream.Position = 0;

            return File(
                memoryStream,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Financial_Orders_Report.xlsx"
            );
        }

        /// <summary>
        /// [PAIR 2 - STREAM EXPORT] Streams full financial report via IAsyncEnumerable.
        /// Feed this output directly to POST /api/financial-orders/import-excel!
        /// </summary>
        [HttpGet("export-stream")]
        public async Task<IActionResult> ExportStreamAsync()
        {
            var memoryStream = new MemoryStream();

            await StreamSampleOrdersAsync().ToExcelAsync(_excelWriter, memoryStream, "Streamed Orders");
            memoryStream.Position = 0;

            return File(
                memoryStream,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Streamed_Orders_Report.xlsx"
            );
        }

        /// <summary>
        /// [PAIR 2 - IMPORT] Reads the 27-column Excel file generated by export-excel or export-stream.
        /// Reads all 27 properties directly back into FinancialOrderDto using FinancialOrderExportProfile!
        /// </summary>
        [HttpPost("import-excel")]
        public IActionResult ImportExportedExcel(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return BadRequest(new { Error = "No file uploaded or file is empty." });

            if (!file.FileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
                return BadRequest(new { Error = "Only .xlsx Excel files are supported." });

            using var stream = file.OpenReadStream();

            // Direct round-trip read using FinancialOrderExportProfile
            var results = _excelReader.Read<FinancialOrderDto, FinancialOrderDto>(stream).ToList();

            var validItems = results.Where(r => r.IsValid).Select(r => r.Data).ToList();
            var invalidItems = results.Where(r => !r.IsValid).Select(r => new
            {
                RowNumber = r.RowIndex,
                Errors = r.Errors
            }).ToList();

            return Ok(new
            {
                Message = "Exported 27-column Excel file read back successfully.",
                TotalRowsRead = results.Count,
                ValidCount = validItems.Count,
                InvalidCount = invalidItems.Count,
                Orders = validItems,
                Errors = invalidItems
            });
        }

        #endregion

        #region 3. Persian RTL Record Endpoints (Matching POST import-records)

        /// <summary>
        /// [PAIR 3 - EXPORT] Exports C# 9+ immutable records with Right-To-Left (RTL) view and Persian headers.
        /// Feed this output directly to POST /api/financial-orders/import-records!
        /// </summary>
        [HttpGet("export-records")]
        public async Task<IActionResult> ExportOrderSummaryRecordsAsync()
        {
            var records = GenerateSampleRecords(10);
            var memoryStream = new MemoryStream();

            await records.ToExcelAsync(_excelWriter, memoryStream, "سفارشات");
            memoryStream.Position = 0;

            return File(
                memoryStream,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Order_Summaries_RTL.xlsx"
            );
        }

        /// <summary>
        /// [PAIR 3 - IMPORT] Reads the Persian RTL Excel file generated by export-records.
        /// Reads columns directly into OrderSummaryRecord using OrderSummaryRecordProfile!
        /// </summary>
        [HttpPost("import-records")]
        public IActionResult ImportOrderSummaryRecords(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return BadRequest(new { Error = "No file uploaded or file is empty." });

            if (!file.FileName.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
                return BadRequest(new { Error = "Only .xlsx Excel files are supported." });

            using var stream = file.OpenReadStream();

            // Direct round-trip read of Persian RTL records
            var results = _excelReader.Read<OrderSummaryRecord, OrderSummaryRecord>(stream).ToList();

            var validRecords = results.Where(r => r.IsValid).Select(r => r.Data).ToList();
            var invalidRecords = results.Where(r => !r.IsValid).Select(r => new
            {
                RowNumber = r.RowIndex,
                Errors = r.Errors
            }).ToList();

            return Ok(new
            {
                Message = "Persian RTL Order Summary Excel file read back successfully.",
                TotalRowsRead = results.Count,
                ValidCount = validRecords.Count,
                InvalidCount = invalidRecords.Count,
                Records = validRecords,
                Errors = invalidRecords
            });
        }

        #endregion

        #region 4. All-in-One Roundtrip Showcase Endpoint

        /// <summary>
        /// [ROUNDTRIP] Accepts raw input Excel (from export-inputs), reads it, runs validation & processing,
        /// and directly writes out a brand new, fully-styled 27-column Excel file.
        /// Demonstrates a complete: Excel In -> Validate -> Enrich -> Excel Out pipeline!
        /// </summary>
        [HttpPost("echo-roundtrip")]
        public async Task<IActionResult> EchoRoundtripAsync(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return BadRequest(new { Error = "No file uploaded or file is empty." });

            using var inputStream = file.OpenReadStream();

            // Step 1: Read and validate raw inputs
            var results = _excelReader.Read<FinancialOrderInput, FinancialOrderDto>(inputStream).ToList();
            var validProcessedOrders = results.Where(r => r.IsValid && r.Data != null).Select(r => r.Data!).ToList();

            if (validProcessedOrders.Count == 0)
            {
                return BadRequest(new
                {
                    Error = "No valid rows found in uploaded file to export.",
                    ValidationErrors = results.Where(r => !r.IsValid).Select(r => new { r.RowIndex, r.Errors })
                });
            }

            // Step 2: Immediately export the processed DTOs with rich styling
            var outputStream = new MemoryStream();
            await _excelWriter.WriteAsync(validProcessedOrders, outputStream, "Processed Orders");
            outputStream.Position = 0;

            return File(
                outputStream,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Financial_Orders_Roundtrip_Result.xlsx"
            );
        }

        #endregion

        #region Helper Sample Generators

        private static List<FinancialOrderInput> GenerateSampleInputs(int count)
        {
            var baseDate = DateOnly.FromDateTime(DateTime.UtcNow);
            var list = new List<FinancialOrderInput>(count);

            for (int i = 1; i <= count; i++)
            {
                list.Add(new FinancialOrderInput
                {
                    TrackingCode = Guid.NewGuid(),
                    CustomerCode = $"CUST-20{i:D2}",
                    CustomerName = $"Customer Name {i}",
                    CompanyName = $"Company {i} Ltd",
                    OrderDate = baseDate.AddDays(-i),
                    DeliveryDate = baseDate.AddDays(i),
                    PreferredDeliveryTime = new TimeOnly(9 + (i % 8), (i * 15) % 60),
                    CreatedAtUtc = DateTime.UtcNow.AddDays(-i),
                    Status = (OrderStatus)(i % 6),
                    Payment = (PaymentMethod)(i % 5),
                    Priority = (PriorityLevel)(i % 4),
                    Quantity = i * 2,
                    UnitPrice = 45.00m + (i * 12.50m),
                    DiscountRate = (i % 3 == 0) ? 0.15m : 0.05m,
                    TaxRate = 0.09m,
                    IsExpressDelivery = (i % 2 == 0),
                    IsInsured = (i % 3 == 0),
                    Tags = new List<string> { "Wholesale", (i % 2 == 0 ? "Priority" : "Standard"), "Tier-1" },
                    Notes = $"Sample input note #{i}."
                });
            }

            return list;
        }

        private static List<FinancialOrderDto> GenerateSampleDtos(int count)
        {
            var baseDate = DateOnly.FromDateTime(DateTime.UtcNow);
            var list = new List<FinancialOrderDto>(count);

            for (int i = 1; i <= count; i++)
            {
                var qty = i * 2;
                var unitPrice = 45.00m + (i * 12.50m);
                var discountRate = (i % 3 == 0) ? 0.15m : 0.05m;
                var subtotal = Math.Round(qty * unitPrice, 2);
                var discountAmount = Math.Round(subtotal * discountRate, 2);
                var taxableAmount = subtotal - discountAmount;
                var taxRate = 0.09m;
                var taxAmount = Math.Round(taxableAmount * taxRate, 2);
                var isExpress = (i % 2 == 0);
                var isInsured = (i % 3 == 0);
                var shippingFee = isExpress ? 25.00m : 5.00m;
                var insuranceFee = isInsured ? 15.00m : 0.00m;

                list.Add(new FinancialOrderDto
                {
                    TrackingCode = Guid.NewGuid(),
                    CustomerCode = $"CUST-20{i:D2}",
                    CustomerName = $"Enterprise Client {i}",
                    CompanyName = $"Global Logistics {i} Ltd",
                    OrderDate = baseDate.AddDays(-i),
                    DeliveryDate = baseDate.AddDays(i),
                    PreferredDeliveryTime = new TimeOnly(9 + (i % 8), (i * 15) % 60),
                    CreatedAtUtc = DateTime.UtcNow.AddDays(-i),
                    Status = (OrderStatus)(i % 6),
                    Payment = (PaymentMethod)(i % 5),
                    Priority = (PriorityLevel)(i % 4),
                    Quantity = qty,
                    UnitPrice = unitPrice,
                    DiscountRate = discountRate,
                    Subtotal = subtotal,
                    DiscountAmount = discountAmount,
                    TaxRate = taxRate,
                    TaxAmount = taxAmount,
                    ShippingFee = shippingFee,
                    InsuranceFee = insuranceFee,
                    TotalAmount = taxableAmount + taxAmount + shippingFee + insuranceFee,
                    IsExpressDelivery = isExpress,
                    IsInsured = isInsured,
                    Tags = new List<string> { "Wholesale", (i % 2 == 0 ? "Priority" : "Standard"), "Tier-1" },
                    SlaStatus = (i % 5 == 0) ? "Due Today / Overdue" : "On Track",
                    ProcessedAtUtc = DateTime.UtcNow,
                    Notes = $"Auto-generated showcase sample order #{i}."
                });
            }

            return list;
        }

        private static List<OrderSummaryRecord> GenerateSampleRecords(int count)
        {
            var baseDate = DateOnly.FromDateTime(DateTime.UtcNow);
            var list = new List<OrderSummaryRecord>(count);

            for (int i = 1; i <= count; i++)
            {
                list.Add(new OrderSummaryRecord(
                    trackingCode: Guid.NewGuid(),
                    customerCode: $"CUST-IR-{1000 + i}",
                    customerName: $"مشتری سازمانی شماره {i}",
                    orderDate: baseDate.AddDays(-i),
                    preferredDeliveryTime: new TimeOnly(10 + (i % 6), 30),
                    quantity: i * 3,
                    totalAmount: 1500.00m + (i * 350.50m),
                    status: (OrderStatus)(i % 6),
                    priority: (PriorityLevel)(i % 4),
                    isExpressDelivery: i % 2 == 0
                ));
            }

            return list;
        }

        private static async IAsyncEnumerable<FinancialOrderDto> StreamSampleOrdersAsync()
        {
            var sample = GenerateSampleDtos(8);
            foreach (var order in sample)
            {
                await Task.Yield();
                yield return order;
            }
        }

        #endregion
    }
}
